/**
 * Badge Definitions
 * Complete badge system for 7% platform
 * 60+ badges across 7 categories
 */

export const BADGE_DEFINITIONS = {
  // ─── DISCIPLINE / STREAK BADGES ──────────────────────────────────────
  discipline: {
    day_1: {
      badge_id: 'day_1',
      name: 'First Step',
      description: 'Completed first day',
      category: 'discipline',
      tier: 'common',
      icon_emoji: '🚀',
      unlock_type: 'streak',
      unlock_value: 1,
      points_awarded: 10,
    },
    streak_3: {
      badge_id: 'streak_3',
      name: '3 Day Streak',
      description: 'Consistency starts here',
      category: 'discipline',
      tier: 'common',
      icon_emoji: '⚡',
      unlock_type: 'streak',
      unlock_value: 3,
      points_awarded: 25,
    },
    streak_7: {
      badge_id: 'streak_7',
      name: '7% Mindset',
      description: 'One week of discipline',
      category: 'discipline',
      tier: 'uncommon',
      icon_emoji: '🔥',
      unlock_type: 'streak',
      unlock_value: 7,
      points_awarded: 50,
    },
    streak_14: {
      badge_id: 'streak_14',
      name: '14 Day Discipline',
      description: 'Two weeks unbroken',
      category: 'discipline',
      tier: 'rare',
      icon_emoji: '💪',
      unlock_type: 'streak',
      unlock_value: 14,
      points_awarded: 100,
    },
    streak_30: {
      badge_id: 'streak_30',
      name: '30 Day Unbroken',
      description: 'A month of commitment',
      category: 'discipline',
      tier: 'elite',
      icon_emoji: '⭐',
      unlock_type: 'streak',
      unlock_value: 30,
      points_awarded: 250,
    },
    streak_60: {
      badge_id: 'streak_60',
      name: '60 Day Consistency',
      description: 'Two months of discipline',
      category: 'discipline',
      tier: 'elite',
      icon_emoji: '✨',
      unlock_type: 'streak',
      unlock_value: 60,
      points_awarded: 500,
    },
    streak_90: {
      badge_id: 'streak_90',
      name: '90 Day Discipline',
      description: 'Three months unbroken',
      category: 'discipline',
      tier: 'legendary',
      icon_emoji: '👑',
      unlock_type: 'streak',
      unlock_value: 90,
      points_awarded: 1000,
    },
    never_miss_twice: {
      badge_id: 'never_miss_twice',
      name: 'Never Miss Twice',
      description: 'Missed → recovered immediately',
      category: 'discipline',
      tier: 'rare',
      icon_emoji: '🎯',
      unlock_type: 'consistency',
      unlock_value: 1,
      points_awarded: 150,
    },
    relentless: {
      badge_id: 'relentless',
      name: 'Relentless',
      description: '14 perfect days, zero misses',
      category: 'discipline',
      tier: 'elite',
      icon_emoji: '🌪️',
      unlock_type: 'consistency',
      unlock_value: 14,
      points_awarded: 300,
    },
    the_7_percent: {
      badge_id: 'the_7_percent',
      name: 'The 7%',
      description: '30+ day streak + leaderboard active',
      category: 'discipline',
      tier: 'legendary',
      icon_emoji: '💎',
      unlock_type: 'milestone',
      unlock_value: 30,
      points_awarded: 1500,
    },

    // ─── EFFORT / ACTIVITY BADGES ────────────────────────────────────────
    first_workout: {
      badge_id: 'first_workout',
      name: 'First Workout',
      description: 'Started the journey',
      category: 'effort',
      tier: 'common',
      icon_emoji: '🏋️',
      unlock_type: 'workout_count',
      unlock_value: 1,
      points_awarded: 10,
    },
    workout_warrior: {
      badge_id: 'workout_warrior',
      name: 'Workout Warrior',
      description: '10 workouts completed',
      category: 'effort',
      tier: 'uncommon',
      icon_emoji: '⚔️',
      unlock_type: 'workout_count',
      unlock_value: 10,
      points_awarded: 50,
    },
    fifty_workouts: {
      badge_id: 'fifty_workouts',
      name: '50 Workouts',
      description: 'Dedication in progress',
      category: 'effort',
      tier: 'rare',
      icon_emoji: '🎖️',
      unlock_type: 'workout_count',
      unlock_value: 50,
      points_awarded: 150,
    },
    hundred_workouts: {
      badge_id: 'hundred_workouts',
      name: '100 Workouts',
      description: 'Century club member',
      category: 'effort',
      tier: 'elite',
      icon_emoji: '🏆',
      unlock_type: 'workout_count',
      unlock_value: 100,
      points_awarded: 500,
    },
    first_meal_logged: {
      badge_id: 'first_meal_logged',
      name: 'Nutrition Tracked',
      description: 'First meal logged',
      category: 'effort',
      tier: 'common',
      icon_emoji: '🍎',
      unlock_type: 'milestone',
      unlock_value: 1,
      points_awarded: 15,
    },
    nutrition_locked_in: {
      badge_id: 'nutrition_locked_in',
      name: 'Nutrition Locked In',
      description: '7 days of meal tracking',
      category: 'effort',
      tier: 'uncommon',
      icon_emoji: '🥗',
      unlock_type: 'milestone',
      unlock_value: 7,
      points_awarded: 75,
    },
    calorie_precision: {
      badge_id: 'calorie_precision',
      name: 'Calorie Precision',
      description: 'Hit target 7 days straight',
      category: 'effort',
      tier: 'rare',
      icon_emoji: '📊',
      unlock_type: 'consistency',
      unlock_value: 7,
      points_awarded: 100,
    },
    protein_focused: {
      badge_id: 'protein_focused',
      name: 'Protein Focused',
      description: 'Hit protein goal 10 days',
      category: 'effort',
      tier: 'rare',
      icon_emoji: '💪',
      unlock_type: 'consistency',
      unlock_value: 10,
      points_awarded: 120,
    },
    consistency_builder: {
      badge_id: 'consistency_builder',
      name: 'Consistency Builder',
      description: '14 full nutrition logs',
      category: 'effort',
      tier: 'elite',
      icon_emoji: '🔨',
      unlock_type: 'consistency',
      unlock_value: 14,
      points_awarded: 250,
    },

    // ─── LEADERBOARD / COMPETITION BADGES ────────────────────────────────
    top_100: {
      badge_id: 'top_100',
      name: 'Top 100',
      description: 'Entered global top 100',
      category: 'leaderboard',
      tier: 'uncommon',
      icon_emoji: '📈',
      unlock_type: 'leaderboard_rank',
      unlock_value: 100,
      points_awarded: 50,
    },
    top_50: {
      badge_id: 'top_50',
      name: 'Top 50',
      description: 'Ranked in top 50 globally',
      category: 'leaderboard',
      tier: 'rare',
      icon_emoji: '🥉',
      unlock_type: 'leaderboard_rank',
      unlock_value: 50,
      points_awarded: 150,
    },
    top_10: {
      badge_id: 'top_10',
      name: 'Elite Tier',
      description: 'Top 10 global ranking',
      category: 'leaderboard',
      tier: 'elite',
      icon_emoji: '🥈',
      unlock_type: 'leaderboard_rank',
      unlock_value: 10,
      points_awarded: 300,
    },
    podium: {
      badge_id: 'podium',
      name: 'Podium Finish',
      description: 'Ranked top 3 this week',
      category: 'leaderboard',
      tier: 'elite',
      icon_emoji: '🥇',
      unlock_type: 'leaderboard_rank',
      unlock_value: 3,
      points_awarded: 400,
    },
    champion: {
      badge_id: 'champion',
      name: 'Champion',
      description: '#1 global ranking',
      category: 'leaderboard',
      tier: 'legendary',
      icon_emoji: '👑',
      unlock_type: 'leaderboard_rank',
      unlock_value: 1,
      points_awarded: 1000,
    },
    back_to_back: {
      badge_id: 'back_to_back',
      name: 'Back-to-Back',
      description: 'Won leaderboard twice',
      category: 'leaderboard',
      tier: 'legendary',
      icon_emoji: '⚡',
      unlock_type: 'milestone',
      unlock_value: 2,
      points_awarded: 800,
    },
    underdog_rise: {
      badge_id: 'underdog_rise',
      name: 'Underdog Rise',
      description: 'Jumped 50 ranks up',
      category: 'leaderboard',
      tier: 'rare',
      icon_emoji: '🚀',
      unlock_type: 'milestone',
      unlock_value: 50,
      points_awarded: 200,
    },
    elite_division: {
      badge_id: 'elite_division',
      name: 'Elite Division',
      description: 'Elite leaderboard member',
      category: 'leaderboard',
      tier: 'elite',
      icon_emoji: '✨',
      unlock_type: 'milestone',
      unlock_value: 1,
      points_awarded: 350,
    },
    world_rank_holder: {
      badge_id: 'world_rank_holder',
      name: 'World Rank Holder',
      description: 'Global Top 10 maintained',
      category: 'leaderboard',
      tier: 'legendary',
      icon_emoji: '🌍',
      unlock_type: 'leaderboard_rank',
      unlock_value: 10,
      points_awarded: 800,
    },

    // ─── LONGEVITY / COMMITMENT BADGES ──────────────────────────────────
    month_member: {
      badge_id: 'month_member',
      name: '1 Month Member',
      description: '30 days active',
      category: 'longevity',
      tier: 'common',
      icon_emoji: '📅',
      unlock_type: 'milestone',
      unlock_value: 30,
      points_awarded: 50,
    },
    three_month_discipline: {
      badge_id: 'three_month_discipline',
      name: '3 Month Discipline',
      description: '90 days active',
      category: 'longevity',
      tier: 'rare',
      icon_emoji: '🔄',
      unlock_type: 'milestone',
      unlock_value: 90,
      points_awarded: 200,
    },
    six_month_commitment: {
      badge_id: 'six_month_commitment',
      name: '6 Month Commitment',
      description: '180 days active',
      category: 'longevity',
      tier: 'elite',
      icon_emoji: '📍',
      unlock_type: 'milestone',
      unlock_value: 180,
      points_awarded: 400,
    },
    one_year_locked_in: {
      badge_id: 'one_year_locked_in',
      name: '1 Year Locked In',
      description: '365 days active',
      category: 'longevity',
      tier: 'legendary',
      icon_emoji: '🎂',
      unlock_type: 'milestone',
      unlock_value: 365,
      points_awarded: 2000,
    },
    never_quit: {
      badge_id: 'never_quit',
      name: 'Never Quit',
      description: 'Returned after break',
      category: 'longevity',
      tier: 'rare',
      icon_emoji: '⭐',
      unlock_type: 'consistency',
      unlock_value: 1,
      points_awarded: 150,
    },
    transformation_phase: {
      badge_id: 'transformation_phase',
      name: 'Transformation Phase',
      description: '60+ active days',
      category: 'longevity',
      tier: 'elite',
      icon_emoji: '🦋',
      unlock_type: 'milestone',
      unlock_value: 60,
      points_awarded: 300,
    },

    // ─── STATUS / PREMIUM BADGES ────────────────────────────────────────
    pro_member: {
      badge_id: 'pro_member',
      name: 'Pro Member',
      description: 'Pro subscription active',
      category: 'status',
      tier: 'rare',
      icon_emoji: '💎',
      unlock_type: 'subscription',
      unlock_value: 1,
      points_awarded: 100,
    },
    elite_member: {
      badge_id: 'elite_member',
      name: 'Elite Member',
      description: 'Elite subscription active',
      category: 'status',
      tier: 'elite',
      icon_emoji: '👑',
      unlock_type: 'subscription',
      unlock_value: 1,
      points_awarded: 200,
    },
    elite_founders: {
      badge_id: 'elite_founders',
      name: 'Elite Founders',
      description: 'Early Elite subscriber',
      category: 'status',
      tier: 'legendary',
      icon_emoji: '🏛️',
      unlock_type: 'subscription',
      unlock_value: 1,
      points_awarded: 500,
    },
    high_performer: {
      badge_id: 'high_performer',
      name: 'High Performer',
      description: 'Top 20% of users',
      category: 'status',
      tier: 'elite',
      icon_emoji: '📊',
      unlock_type: 'milestone',
      unlock_value: 1,
      points_awarded: 250,
    },
    serious_about_progress: {
      badge_id: 'serious_about_progress',
      name: 'Serious About Progress',
      description: '30+ streak + Pro member',
      category: 'status',
      tier: 'elite',
      icon_emoji: '🎯',
      unlock_type: 'milestone',
      unlock_value: 30,
      points_awarded: 300,
    },

    // ─── SPECIAL IDENTITY BADGES ────────────────────────────────────────
    most_people_quit: {
      badge_id: 'most_people_quit',
      name: 'Most People Quit',
      description: '7-day streak (they don\'t)',
      category: 'identity',
      tier: 'uncommon',
      icon_emoji: '🎯',
      unlock_type: 'streak',
      unlock_value: 7,
      points_awarded: 75,
    },
    built_different: {
      badge_id: 'built_different',
      name: 'Built Different',
      description: '30 workouts completed',
      category: 'identity',
      tier: 'rare',
      icon_emoji: '💪',
      unlock_type: 'workout_count',
      unlock_value: 30,
      points_awarded: 150,
    },
    silent_work: {
      badge_id: 'silent_work',
      name: 'Silent Work',
      description: '14 days, zero misses',
      category: 'identity',
      tier: 'rare',
      icon_emoji: '🤐',
      unlock_type: 'consistency',
      unlock_value: 14,
      points_awarded: 125,
    },
    outlasted_motivation: {
      badge_id: 'outlasted_motivation',
      name: 'Outlasted Motivation',
      description: '21-day streak',
      category: 'identity',
      tier: 'elite',
      icon_emoji: '⚡',
      unlock_type: 'streak',
      unlock_value: 21,
      points_awarded: 200,
    },
    consistency_over_motivation: {
      badge_id: 'consistency_over_motivation',
      name: 'Consistency > Motivation',
      description: '45-day streak',
      category: 'identity',
      tier: 'elite',
      icon_emoji: '🔥',
      unlock_type: 'streak',
      unlock_value: 45,
      points_awarded: 350,
    },
    discipline_icon: {
      badge_id: 'discipline_icon',
      name: 'Discipline Icon',
      description: '90+ day streak',
      category: 'identity',
      tier: 'legendary',
      icon_emoji: '🗽',
      unlock_type: 'streak',
      unlock_value: 90,
      points_awarded: 1200,
    },

    // ─── SEASONAL / EVENT BADGES ────────────────────────────────────────
    new_year_lock_in: {
      badge_id: 'new_year_lock_in',
      name: 'New Year Lock-In',
      description: 'January consistency',
      category: 'seasonal',
      tier: 'rare',
      icon_emoji: '🎆',
      unlock_type: 'event',
      unlock_value: 1,
      points_awarded: 100,
    },
    summer_discipline: {
      badge_id: 'summer_discipline',
      name: 'Summer Grind',
      description: 'Summer challenge complete',
      category: 'seasonal',
      tier: 'rare',
      icon_emoji: '☀️',
      unlock_type: 'event',
      unlock_value: 1,
      points_awarded: 100,
    },
    winter_grind: {
      badge_id: 'winter_grind',
      name: 'Winter Grind',
      description: 'Winter challenge complete',
      category: 'seasonal',
      tier: 'rare',
      icon_emoji: '❄️',
      unlock_type: 'event',
      unlock_value: 1,
      points_awarded: 100,
    },
    perfect_week: {
      badge_id: 'perfect_week',
      name: 'Perfect Week',
      description: '7 days zero misses',
      category: 'seasonal',
      tier: 'uncommon',
      icon_emoji: '✅',
      unlock_type: 'consistency',
      unlock_value: 7,
      points_awarded: 75,
    },

    // ─── ULTRA-RARE LEGENDARY BADGES ────────────────────────────────────
    hundred_day_unbroken: {
      badge_id: 'hundred_day_unbroken',
      name: '100 Day Unbroken',
      description: '100 days unbroken',
      category: 'discipline',
      tier: 'legendary',
      icon_emoji: '💯',
      unlock_type: 'streak',
      unlock_value: 100,
      points_awarded: 1500,
    },
    top_1_global: {
      badge_id: 'top_1_global',
      name: 'Top 1 Global',
      description: '#1 in the world',
      category: 'leaderboard',
      tier: 'legendary',
      icon_emoji: '🌟',
      unlock_type: 'leaderboard_rank',
      unlock_value: 1,
      points_awarded: 2000,
    },
    one_percent_of_7_percent: {
      badge_id: 'one_percent_of_7_percent',
      name: 'The 1% of the 7%',
      description: 'Peak discipline tier',
      category: 'identity',
      tier: 'legendary',
      icon_emoji: '👾',
      unlock_type: 'milestone',
      unlock_value: 1,
      points_awarded: 2500,
    },
    never_missed_month: {
      badge_id: 'never_missed_month',
      name: 'Never Missed Month',
      description: 'Perfect month (30 days)',
      category: 'discipline',
      tier: 'legendary',
      icon_emoji: '📆',
      unlock_type: 'consistency',
      unlock_value: 30,
      points_awarded: 800,
    },
    perfect_365: {
      badge_id: 'perfect_365',
      name: '365 Perfect Days',
      description: 'A year of perfection',
      category: 'longevity',
      tier: 'legendary',
      icon_emoji: '🏅',
      unlock_type: 'milestone',
      unlock_value: 365,
      points_awarded: 3000,
    },
  },
};

export const getBadgeById = (badgeId) => {
  for (const category in BADGE_DEFINITIONS) {
    if (BADGE_DEFINITIONS[category][badgeId]) {
      return BADGE_DEFINITIONS[category][badgeId];
    }
  }
  return null;
};

export const getAllBadges = () => {
  const all = [];
  for (const category in BADGE_DEFINITIONS) {
    for (const badgeId in BADGE_DEFINITIONS[category]) {
      all.push(BADGE_DEFINITIONS[category][badgeId]);
    }
  }
  return all;
};

export const getBadgesByCategory = (category) => {
  return Object.values(BADGE_DEFINITIONS[category] || {});
};

export const getBadgesByTier = (tier) => {
  return getAllBadges().filter(b => b.tier === tier);
};

export const TIER_COLORS = {
  common: { bg: 'bg-gray-500/10', text: 'text-gray-400', border: 'border-gray-500/20' },
  uncommon: { bg: 'bg-blue-500/10', text: 'text-blue-400', border: 'border-blue-500/20' },
  rare: { bg: 'bg-purple-500/10', text: 'text-purple-400', border: 'border-purple-500/20' },
  elite: { bg: 'bg-amber-500/10', text: 'text-amber-400', border: 'border-amber-500/20' },
  legendary: { bg: 'bg-yellow-500/10', text: 'text-yellow-300', border: 'border-yellow-500/30' },
};

export const CATEGORY_ICONS = {
  discipline: '🔥',
  effort: '💪',
  leaderboard: '🏆',
  longevity: '📅',
  status: '💎',
  identity: '⭐',
  seasonal: '🎭',
};